name: Deploy to Amazon ECS environment based on branch

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:                                                            
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::182093768440:role/github-role
        aws-region: ap-south-1
    - name: Geting Latest Task Definition from ECS
      id: ecs-task-def
      run: |
        aws sts get-caller-identity
  
