name: Deploy to Amazon ECS environment based on branch

on:
  push:
    branches:
      - main
      - release
      - dev
     

       
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    

    steps:                                                            
    - name: Build and Deploy to ECS 
      uses: leelaprakash/gh-actions-automation-ecs-central@v1
      with:
        ecr-repo: "leela-test-gh-actions"
        ecs-service: "nginx-test" 
        task-definition: "first-run-task-definition"
