name: Deploy to Amazon ECS environment based on branch

on:
  push:
    branches:
      - main
      - release
      - dev
     

       
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:                                                            
    - name: ECS Automation
      uses: leelaprakash/gh-actions-automation-ecs-central@vf
      with:
        ecr-repo: "leela-test-gh-actions"
        ecs-service: "nginx-test" 
        task-definition: "first-run-task-definition"
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
